import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import Tour from '../models/Tour.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '../../.env') });

const tours = [
  {
    title: 'Himalayan Base Camp Trek',
    description: 'A breathtaking 10-day journey through the mighty Himalayas. Trek through ancient villages, rhododendron forests, and glacial moraines to reach the legendary Everest Base Camp at 5364m.',
    price: 1299,
    duration: 10,
    maxGroupSize: 12,
    difficulty: 'difficult',
    location: 'Kathmandu',
    country: 'Nepal',
    coordinates: { lat: 27.9881, lng: 86.9250 },
    featured: true,
    rating: 4.9,
    ratingsCount: 128,
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Kathmandu',
        description: 'Arrive at Tribhuvan International Airport. Transfer to hotel and evening briefing with your trek guide.',
        activities: ['Airport pickup', 'Hotel check-in', 'Trek briefing', 'Welcome dinner'],
        accommodation: 'Hotel Yak & Yeti, Kathmandu',
        meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2,
        title: 'Fly to Lukla — Trek to Phakding',
        description: 'Early morning flight to Lukla (2840m). Begin trekking through pine forests to Phakding village.',
        activities: ['Scenic mountain flight', 'Trek through Chaurikharka', 'Cross suspension bridges'],
        accommodation: 'Phakding Guesthouse',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 3,
        title: 'Phakding to Namche Bazaar',
        description: 'Trek to the bustling Sherpa capital of Namche Bazaar (3440m). Steep climb with first views of Everest.',
        activities: ['Sagarmatha National Park entry', 'First Everest viewpoint', 'Namche market visit'],
        accommodation: 'Hotel Khumbu, Namche',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 4,
        title: 'Acclimatization Day in Namche',
        description: 'Rest day to acclimatize. Optional hike to Everest View Hotel for panoramic Himalayan views.',
        activities: ['Hike to Everest View Hotel', 'Visit Sherpa Culture Museum', 'Explore Namche market'],
        accommodation: 'Hotel Khumbu, Namche',
        meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 5,
        title: 'Namche to Tengboche',
        description: 'Trek to Tengboche (3860m), home to the famous Tengboche Monastery with stunning Ama Dablam views.',
        activities: ['Tengboche Monastery visit', 'Panoramic mountain views', 'Afternoon meditation session'],
        accommodation: 'Tengboche Guesthouse',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 6,
        title: 'Tengboche to Dingboche',
        description: 'Continue through Pangboche village to the wide valley of Dingboche (4410m).',
        activities: ['Pangboche Monastery', 'Imja Khola valley walk', 'High altitude acclimatization'],
        accommodation: 'Dingboche Inn',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 7,
        title: 'Acclimatization Hike to Nagarjun Hill',
        description: 'Rest and acclimatization day with optional hike to Nagarjun Hill (5100m) for 360° Himalayan views.',
        activities: ['Summit Nagarjun Hill', 'View of Makalu and Lhotse', 'Rest and hydration'],
        accommodation: 'Dingboche Inn',
        meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 8,
        title: 'Dingboche to Lobuche',
        description: 'Trek past the Thukla memorial chortens to Lobuche (4940m). Incredible views of Khumbu Glacier.',
        activities: ['Thukla Pass memorial', 'Khumbu Glacier views', 'High altitude camping'],
        accommodation: 'Lobuche Guest House',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 9,
        title: 'Lobuche to Everest Base Camp',
        description: 'The epic day — trek to Gorak Shep then on to Everest Base Camp (5364m). Celebrate at the top of the world!',
        activities: ['Reach Everest Base Camp', 'Khumbu Icefall views', 'Gorak Shep lunch', 'Sunset views'],
        accommodation: 'Gorak Shep Lodge',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 10,
        title: 'Kala Patthar Sunrise — Fly back to Kathmandu',
        description: 'Pre-dawn hike to Kala Patthar (5545m) for the most iconic Everest sunrise. Descend to Lukla and fly back.',
        activities: ['Kala Patthar sunrise', 'Best Everest photo spot', 'Descend to Lukla', 'Celebration dinner'],
        accommodation: 'Hotel Yak & Yeti, Kathmandu',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
    ],
  },
  {
    title: 'Bali Spiritual Journey',
    description: 'Immerse yourself in Balinese culture with temple visits, traditional ceremonies, rice terrace walks, and cooking classes.',
    price: 899,
    duration: 7,
    maxGroupSize: 10,
    difficulty: 'easy',
    location: 'Ubud',
    country: 'Indonesia',
    coordinates: { lat: -8.5069, lng: 115.2625 },
    featured: true,
    rating: 4.8,
    ratingsCount: 95,
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bali',
        description: 'Arrive at Ngurah Rai International Airport. Transfer to Ubud through terraced rice fields.',
        activities: ['Airport transfer', 'Ubud Palace visit', 'Kecak fire dance performance'],
        accommodation: 'Komaneka Resort, Ubud',
        meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2,
        title: 'Sacred Temples & Rice Terraces',
        description: 'Visit Tegallalang rice terraces at sunrise, then explore Tirta Empul holy spring temple.',
        activities: ['Tegallalang rice terraces', 'Tirta Empul purification ritual', 'Traditional lunch'],
        accommodation: 'Komaneka Resort, Ubud',
        meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 3,
        title: 'Balinese Cooking Class',
        description: 'Morning market visit followed by hands-on traditional Balinese cooking class with a local family.',
        activities: ['Ubud morning market', 'Cooking class', 'Learn 5 traditional dishes', 'Afternoon free time'],
        accommodation: 'Komaneka Resort, Ubud',
        meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 4,
        title: 'Mount Batur Sunrise Trek',
        description: 'Pre-dawn hike up the active volcano Mount Batur for a spectacular sunrise above the clouds.',
        activities: ['Mount Batur sunrise trek', 'Volcanic crater views', 'Hot spring soak', 'Coffee plantation visit'],
        accommodation: 'Komaneka Resort, Ubud',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 5,
        title: 'Meditation & Healing',
        description: 'Private session with a Balinese healer, afternoon yoga overlooking the jungle, sound bath ceremony.',
        activities: ['Balinese healer session', 'Jungle yoga', 'Sound bath ceremony', 'Spa treatment'],
        accommodation: 'Komaneka Resort, Ubud',
        meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 6,
        title: 'Tanah Lot & Seminyak Beach',
        description: 'Visit the iconic sea temple Tanah Lot at sunset, then evening in Seminyak beach area.',
        activities: ['Tanah Lot temple', 'Sunset ceremony', 'Seminyak beach', 'Seafood dinner'],
        accommodation: 'The Layar Villa, Seminyak',
        meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 7,
        title: 'Farewell Morning & Departure',
        description: 'Final morning at leisure, last beach walk, and transfer to the airport with beautiful memories.',
        activities: ['Morning beach walk', 'Souvenir shopping', 'Airport transfer'],
        accommodation: '',
        meals: { breakfast: true, lunch: false, dinner: false },
      },
    ],
  },
  {
    title: 'Santorini Island Escape',
    description: 'Explore the iconic white-washed villages, volcanic beaches, and world-famous sunsets of Santorini.',
    price: 1599,
    duration: 6,
    maxGroupSize: 8,
    difficulty: 'easy',
    location: 'Oia',
    country: 'Greece',
    coordinates: { lat: 36.4618, lng: 25.3753 },
    featured: true,
    rating: 4.7,
    ratingsCount: 76,
    coverImage: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Santorini',
        description: 'Fly into Santorini airport or arrive by ferry. Check into clifftop hotel with caldera views.',
        activities: ['Check-in', 'Fira town exploration', 'Welcome cocktails at sunset'],
        accommodation: 'Canaves Oia Suites',
        meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2,
        title: 'Oia Village & Volcanic Beaches',
        description: 'Morning walk through Oia\'s blue-domed churches, afternoon at the unique Red Beach.',
        activities: ['Oia village walk', 'Red Beach swim', 'Local wine tasting', 'Oia sunset'],
        accommodation: 'Canaves Oia Suites',
        meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 3,
        title: 'Sailing & Volcano Tour',
        description: 'Full day catamaran sailing around the caldera, snorkeling at hot springs, and volcano hike.',
        activities: ['Catamaran sailing', 'Hot spring snorkeling', 'Volcano hike', 'BBQ on boat'],
        accommodation: 'Canaves Oia Suites',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 4,
        title: 'Wine Tour & Ancient Akrotiri',
        description: 'Visit the prehistoric ruins of Akrotiri, then tour three of Santorini\'s finest wineries.',
        activities: ['Akrotiri excavation site', 'Santo Wines tour', 'Wine and local cheese tasting'],
        accommodation: 'Canaves Oia Suites',
        meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 5,
        title: 'Fira to Oia Caldera Hike',
        description: 'The famous 10km clifftop trail from Fira to Oia with breathtaking caldera views throughout.',
        activities: ['Caldera rim hike', 'Imerovigli viewpoint', 'Skaros Rock', 'Oia arrival celebration'],
        accommodation: 'Canaves Oia Suites',
        meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 6,
        title: 'Leisure Morning & Departure',
        description: 'Final morning at the pool, last views of the caldera, and transfer to airport or port.',
        activities: ['Pool morning', 'Last caldera views', 'Souvenir shopping', 'Departure'],
        accommodation: '',
        meals: { breakfast: true, lunch: false, dinner: false },
      },
    ],
  },
  {
  title: 'Indore Cultural & Food Explorer',
  description: 'Discover the heart of Madhya Pradesh with a vibrant journey through Indore’s royal heritage, spiritual sites, and India’s cleanest city charm. Experience iconic palaces, street food heaven, and nearby historical gems like Mandu.',
  price: 299,
  duration: 4,
  maxGroupSize: 15,
  difficulty: 'easy',
  location: 'Indore',
  country: 'India',
  coordinates: { lat: 22.7196, lng: 75.8577 },
  featured: true,
  rating: 4.6,
  ratingsCount: 89,
  coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80',

  itinerary: [
    {
      day: 1,
      title: 'Arrival in Indore & City Introduction',
      description: 'Arrive in Indore and check into your hotel. Begin with a visit to Rajwada Palace and explore local markets. End the day at the famous Sarafa Bazaar night food market.',
      activities: [
        'Hotel check-in',
        'Visit Rajwada Palace',
        'Khajuri Bazaar shopping',
        'Sarafa Bazaar street food tour'
      ],
      accommodation: 'Hotel Amar Vilas, Indore',
      meals: { breakfast: false, lunch: false, dinner: true },
    },
    {
      day: 2,
      title: 'Heritage & Food Exploration',
      description: 'Visit Lal Bagh Palace showcasing royal Holkar history. Explore Central Museum and enjoy Indore’s famous breakfast at Chappan Dukan.',
      activities: [
        'Lal Bagh Palace visit',
        'Central Museum tour',
        'Chappan Dukan breakfast',
        'Cafe hopping'
      ],
      accommodation: 'Hotel Amar Vilas, Indore',
      meals: { breakfast: true, lunch: true, dinner: false },
    },
    {
      day: 3,
      title: 'Excursion to Mandu',
      description: 'Day trip to Mandu, the city of joy, known for Afghan architecture and romantic ruins like Jahaz Mahal and Rani Roopmati Pavilion.',
      activities: [
        'Drive to Mandu',
        'Visit Jahaz Mahal',
        'Explore Hindola Mahal',
        'Rani Roopmati Pavilion sunset'
      ],
      accommodation: 'Hotel Amar Vilas, Indore',
      meals: { breakfast: true, lunch: true, dinner: true },
    },
    {
      day: 4,
      title: 'Temples & Departure',
      description: 'Visit Khajrana Ganesh Temple for blessings and enjoy some last-minute shopping before departure.',
      activities: [
        'Khajrana Ganesh Temple visit',
        'Local shopping',
        'Check-out & departure'
      ],
      accommodation: '',
      meals: { breakfast: true, lunch: false, dinner: false },
    }
  ]
},
  {
    title: 'Sahara Desert Adventure',
    description: 'Ride camels across golden dunes, sleep under a million stars in a Bedouin camp.',
    price: 749,
    duration: 5,
    maxGroupSize: 15,
    difficulty: 'medium',
    location: 'Merzouga',
    country: 'Morocco',
    coordinates: { lat: 31.0997, lng: -4.0114 },
    featured: false,
    rating: 4.6,
    ratingsCount: 54,
    coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    itinerary: [
      {
        day: 1, title: 'Arrive Marrakech', description: 'Arrive and explore the famous Djemaa el-Fna square.',
        activities: ['Medina walk', 'Souks exploration', 'Snake charmers and storytellers'],
        accommodation: 'Riad Kniza, Marrakech', meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2, title: 'Drive to the Desert', description: 'Scenic drive through the Atlas Mountains and Draa Valley to Merzouga.',
        activities: ['Atlas Mountains crossing', 'Kasbah Ait Ben Haddou', 'Draa Valley oasis'],
        accommodation: 'Kasbah Tombouctou', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 3, title: 'Camel Trek & Bivouac', description: 'Sunset camel trek into the Erg Chebbi dunes, overnight in luxury Bedouin camp.',
        activities: ['Camel trek at sunset', 'Dune sandboarding', 'Stargazing', 'Traditional music around fire'],
        accommodation: 'Luxury Bedouin Bivouac', meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 4, title: 'Sunrise Dunes & Fes Drive', description: 'Watch sunrise from the top of the tallest dune, then drive to Fes.',
        activities: ['Sunrise dune climb', 'Berber village visit', 'Fes medina entry'],
        accommodation: 'Riad Fes', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 5, title: 'Fes & Departure', description: 'Morning tour of Fes el-Bali, the world\'s largest car-free urban area.',
        activities: ['Fes tanneries', 'Al-Qarawiyyin mosque', 'Departure transfer'],
        accommodation: '', meals: { breakfast: true, lunch: false, dinner: false },
      },
    ],
  },
  {
    title: 'Tokyo City Explorer',
    description: 'Dive deep into the electric energy of Tokyo — ancient shrines to futuristic neighborhoods.',
    price: 1099,
    duration: 7,
    maxGroupSize: 12,
    difficulty: 'easy',
    location: 'Tokyo',
    country: 'Japan',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    featured: true,
    rating: 4.8,
    ratingsCount: 110,
    coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    itinerary: [
      {
        day: 1, title: 'Arrival & Shinjuku', description: 'Arrive at Narita or Haneda. Evening in neon-lit Shinjuku.',
        activities: ['Shinjuku Gyoen garden', 'Golden Gai bar alley', 'Kabukicho walk'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2, title: 'Asakusa & Akihabara', description: 'Traditional meets futuristic — Senso-ji temple to Electric Town.',
        activities: ['Senso-ji Temple', 'Nakamise shopping street', 'Akihabara electronics', 'Maid cafe'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 3, title: 'Shibuya & Harajuku', description: 'Cross the world\'s busiest intersection and explore Harajuku street fashion.',
        activities: ['Shibuya crossing', 'Meiji Shrine', 'Takeshita Street', 'Omotesando shopping'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 4, title: 'Day Trip to Nikko', description: 'UNESCO World Heritage shrines and waterfalls in the mountains near Tokyo.',
        activities: ['Tosho-gu Shrine', 'Kegon Falls', 'Lake Chuzenji', 'Cedar avenue walk'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 5, title: 'Tsukiji & Teamlab', description: 'Morning at the outer Tsukiji market, evening at the incredible digital art museum.',
        activities: ['Tsukiji breakfast', 'Sushi making class', 'Teamlab Planets', 'Odaiba waterfront'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 6, title: 'Ramen Tour & Karaoke Night', description: 'Dedicated ramen tour across Tokyo\'s best bowls, ending with karaoke.',
        activities: ['Ichiran Ramen', 'Fuunji Tsukemen', 'Afuri Ramen', 'Karaoke box night'],
        accommodation: 'Park Hyatt Tokyo', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 7, title: 'Yanaka & Departure', description: 'Final morning in old-town Yanaka, Tokyo\'s most historic neighbourhood.',
        activities: ['Yanaka cemetery walk', 'Yanaka Ginza street', 'Airport transfer'],
        accommodation: '', meals: { breakfast: true, lunch: false, dinner: false },
      },
    ],
  },
  {
    title: 'Rajasthan Royal Tour',
    description: 'Journey through the land of maharajas — grand forts, colorful bazaars, and palace hotels.',
    price: 999,
    duration: 9,
    maxGroupSize: 14,
    difficulty: 'easy',
    location: 'Jaipur',
    country: 'India',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    featured: true,
    rating: 4.6,
    ratingsCount: 89,
    coverImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80',
    itinerary: [
      {
        day: 1, title: 'Arrive in Jaipur', description: 'The Pink City welcomes you. Evening at Nahargarh Fort for sunset views.',
        activities: ['Nahargarh Fort sunset', 'Chokhi Dhani village dinner', 'Rajasthani folk performance'],
        accommodation: 'Rambagh Palace', meals: { breakfast: false, lunch: false, dinner: true },
      },
      {
        day: 2, title: 'Jaipur Palaces & Forts', description: 'Explore Amber Fort, City Palace, and the iconic Hawa Mahal.',
        activities: ['Amber Fort elephant ride', 'City Palace', 'Hawa Mahal', 'Jantar Mantar'],
        accommodation: 'Rambagh Palace', meals: { breakfast: true, lunch: true, dinner: false },
      },
      {
        day: 3, title: 'Drive to Pushkar', description: 'Sacred lake city of Pushkar with its only Brahma temple in the world.',
        activities: ['Pushkar Lake ghats', 'Brahma Temple', 'Camel market', 'Sunset aarti ceremony'],
        accommodation: 'Dera Masuda, Pushkar', meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 4, title: 'Jodhpur — The Blue City', description: 'Drive to Jodhpur and explore the massive Mehrangarh Fort.',
        activities: ['Mehrangarh Fort', 'Blue City walk', 'Clock Tower market', 'Rooftop dinner'],
        accommodation: 'RAAS Jodhpur', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 5, title: 'Osian Desert & Camel Safari', description: 'Visit ancient Osian temples then camel safari into the Thar Desert.',
        activities: ['Osian temple complex', 'Camel safari', 'Desert camp bonfire', 'Rajasthani music'],
        accommodation: 'Desert Camp, Osian', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 6, title: 'Jaisalmer — The Golden City', description: 'The magnificent sandstone city that glows golden at sunset.',
        activities: ['Jaisalmer Fort', 'Patwon ki Haveli', 'Gadisar Lake', 'Golden city walk'],
        accommodation: 'Suryagarh Palace', meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 7, title: 'Sam Sand Dunes', description: 'Sunrise jeep safari to Sam Sand Dunes, the heart of the Thar Desert.',
        activities: ['Sunrise jeep safari', 'Dune climb', 'Village visit', 'Camel polo'],
        accommodation: 'Suryagarh Palace', meals: { breakfast: true, lunch: true, dinner: true },
      },
      {
        day: 8, title: 'Udaipur — City of Lakes', description: 'The most romantic city in India, built around shimmering lakes.',
        activities: ['Lake Pichola boat ride', 'City Palace', 'Jagdish Temple', 'Sunset cruise'],
        accommodation: 'Taj Lake Palace', meals: { breakfast: true, lunch: false, dinner: true },
      },
      {
        day: 9, title: 'Udaipur Morning & Departure', description: 'Final morning at the lake palace, shopping for handicrafts.',
        activities: ['Saheliyon ki Bari garden', 'Handicraft shopping', 'Airport transfer'],
        accommodation: '', meals: { breakfast: true, lunch: false, dinner: false },
      },
    ],
  },
  {
    title: 'Patagonia Wilderness Trek',
    description: 'Hike through the dramatic landscapes of Torres del Paine.',
    price: 1899,
    duration: 12,
    maxGroupSize: 10,
    difficulty: 'difficult',
    location: 'Puerto Natales',
    country: 'Chile',
    coordinates: { lat: -50.9423, lng: -73.4068 },
    featured: false,
    rating: 4.9,
    ratingsCount: 42,
    coverImage: 'https://images.unsplash.com/photo-1531761535209-83f696c29ff5?w=800&q=80',
    itinerary: [
      { day: 1, title: 'Arrive Puerto Natales', description: 'Arrive and gear check for the W trek.', activities: ['Gear check', 'Trek briefing', 'Town exploration'], accommodation: 'Singular Patagonia Hotel', meals: { breakfast: false, lunch: false, dinner: true } },
      { day: 2, title: 'Enter Torres del Paine', description: 'Enter the park and trek to Chileno camp.', activities: ['Park entry', 'Forest trek', 'River crossings'], accommodation: 'Chileno Camp', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 3, title: 'Torres del Paine Summit', description: 'The iconic sunrise hike to the base of the three towers.', activities: ['Pre-dawn hike', 'Torres viewpoint', 'Sunrise photos'], accommodation: 'Chileno Camp', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 4, title: 'Valle del Francés', description: 'Trek through the French Valley with hanging glaciers overhead.', activities: ['French Valley hike', 'Glacier views', 'Condor spotting'], accommodation: 'Italiano Camp', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 5, title: 'Grey Glacier', description: 'Hike to the stunning Grey Glacier on the edge of the Southern Patagonian Ice Field.', activities: ['Grey Glacier hike', 'Iceberg walk', 'Glacier kayaking'], accommodation: 'Grey Camp', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 6, title: 'Rest Day', description: 'Rest and explore around Grey Lake.', activities: ['Lake kayaking', 'Wildlife spotting', 'Relaxation'], accommodation: 'Grey Camp', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 7, title: 'Return Trek Day 1', description: 'Begin return journey through the park.', activities: ['Scenic return trek', 'Guanaco spotting', 'Photography'], accommodation: 'Pehoe Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 8, title: 'Return Trek Day 2', description: 'Complete the W circuit back to park entrance.', activities: ['Final trek section', 'Park exit', 'Celebration dinner'], accommodation: 'Singular Patagonia Hotel', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 9, title: 'Puerto Williams Day Trip', description: 'Day trip to the world\'s southernmost city.', activities: ['Puerto Williams visit', 'Beagle Channel', 'Yaghan culture museum'], accommodation: 'Singular Patagonia Hotel', meals: { breakfast: true, lunch: true, dinner: false } },
      { day: 10, title: 'Punta Arenas', description: 'Drive to Punta Arenas, gateway to Antarctica.', activities: ['Magellan Strait viewpoint', 'Penguin colony visit', 'City tour'], accommodation: 'Hotel Jose Nogueira', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 11, title: 'Farewell Patagonia', description: 'Final day exploring Punta Arenas.', activities: ['Cemetery walk', 'Local market', 'Farewell dinner'], accommodation: 'Hotel Jose Nogueira', meals: { breakfast: true, lunch: false, dinner: true } },
      { day: 12, title: 'Departure', description: 'Transfer to Punta Arenas airport and fly home.', activities: ['Airport transfer', 'Departure'], accommodation: '', meals: { breakfast: true, lunch: false, dinner: false } },
    ],
  },
  {
    title: 'Amazon Rainforest Expedition',
    description: 'Venture deep into the Amazon basin with expert naturalist guides.',
    price: 1450,
    duration: 8,
    maxGroupSize: 8,
    difficulty: 'medium',
    location: 'Manaus',
    country: 'Brazil',
    coordinates: { lat: -3.1190, lng: -60.0217 },
    featured: false,
    rating: 4.7,
    ratingsCount: 38,
    coverImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80',
    itinerary: [
      { day: 1, title: 'Arrive Manaus', description: 'Arrive in Manaus, gateway to the Amazon. Evening river cruise.', activities: ['Teatro Amazonas opera house', 'Meeting of the Waters', 'Welcome dinner'], accommodation: 'Tropical Manaus Hotel', meals: { breakfast: false, lunch: false, dinner: true } },
      { day: 2, title: 'Enter the Jungle', description: 'Speedboat deep into the Amazon to your jungle lodge.', activities: ['Speedboat jungle transfer', 'Piranha fishing', 'Jungle survival skills'], accommodation: 'Anavilhanas Jungle Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 3, title: 'Wildlife Morning Trek', description: 'Early morning trek with naturalist guide to spot monkeys, sloths, and exotic birds.', activities: ['Bird watching at dawn', 'Monkey spotting', 'Medicinal plants tour'], accommodation: 'Anavilhanas Jungle Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 4, title: 'Indigenous Village Visit', description: 'Visit a traditional indigenous community to learn about ancient Amazonian culture.', activities: ['Yanomami village', 'Traditional crafts', 'Jungle cooking class'], accommodation: 'Anavilhanas Jungle Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 5, title: 'Flooded Forest Canoe', description: 'Canoe through the flooded igapó forest, an otherworldly experience.', activities: ['Igapó forest canoe', 'Pink dolphin spotting', 'Sunset on the river'], accommodation: 'Anavilhanas Jungle Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 6, title: 'Night Safari', description: 'Night boat safari to spot caimans, tree frogs, and other nocturnal creatures.', activities: ['Night boat safari', 'Caiman spotting', 'Tarantula tracking'], accommodation: 'Anavilhanas Jungle Lodge', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 7, title: 'Return to Manaus', description: 'Return journey to Manaus with floating market visit.', activities: ['Floating market', 'City tour', 'Farewell dinner'], accommodation: 'Tropical Manaus Hotel', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 8, title: 'Departure', description: 'Transfer to Eduardo Gomes International Airport.', activities: ['Last river view', 'Airport transfer'], accommodation: '', meals: { breakfast: true, lunch: false, dinner: false } },
    ],
  },
  {
    title: 'Amalfi Coast Road Trip',
    description: 'Drive the legendary Amalfi Coast, stopping at colorful fishing villages and hidden beaches.',
    price: 1350,
    duration: 8,
    maxGroupSize: 10,
    difficulty: 'easy',
    location: 'Amalfi',
    country: 'Italy',
    coordinates: { lat: 40.6340, lng: 14.6027 },
    featured: false,
    rating: 4.8,
    ratingsCount: 67,
    coverImage: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800&q=80',
    itinerary: [
      { day: 1, title: 'Arrive Naples', description: 'Arrive in Naples, pizza capital of the world.', activities: ['Spaccanapoli street walk', 'Pizza making class', 'Vesuvius views'], accommodation: 'Romeo Hotel Naples', meals: { breakfast: false, lunch: false, dinner: true } },
      { day: 2, title: 'Pompeii & Positano', description: 'Morning at Pompeii ruins, afternoon arrival in glamorous Positano.', activities: ['Pompeii excavation', 'Positano beach', 'Cliffside aperitivo'], accommodation: 'Le Sirenuse, Positano', meals: { breakfast: true, lunch: true, dinner: false } },
      { day: 3, title: 'Path of the Gods Hike', description: 'The famous coastal hiking trail with jaw-dropping views of the Tyrrhenian Sea.', activities: ['Path of the Gods hike', 'Nocelle village', 'Cliff swimming'], accommodation: 'Le Sirenuse, Positano', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 4, title: 'Amalfi Town & Ravello', description: 'Explore Amalfi Cathedral and the hilltop gardens of Ravello.', activities: ['Amalfi Cathedral', 'Ravello Villa Cimbrone', 'Limoncello tasting'], accommodation: 'Santa Caterina, Amalfi', meals: { breakfast: true, lunch: false, dinner: true } },
      { day: 5, title: 'Capri Day Trip', description: 'Ferry to the glamorous island of Capri, Blue Grotto, and Villa Jovis.', activities: ['Blue Grotto boat tour', 'Villa Jovis', 'Capri town shopping', 'Sunset cocktails'], accommodation: 'Santa Caterina, Amalfi', meals: { breakfast: true, lunch: true, dinner: false } },
      { day: 6, title: 'Sorrento & Cooking Class', description: 'Charming Sorrento with hands-on Italian cooking class using local ingredients.', activities: ['Sorrento town walk', 'Cooking class', 'Market visit', 'Pasta and tiramisu making'], accommodation: 'Excelsior Vittoria, Sorrento', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 7, title: 'Paestum Greek Temples', description: 'Visit the remarkably well-preserved Greek temples, older than the Parthenon.', activities: ['Paestum temples', 'Mozzarella farm visit', 'Buffalo mozzarella tasting'], accommodation: 'Excelsior Vittoria, Sorrento', meals: { breakfast: true, lunch: true, dinner: true } },
      { day: 8, title: 'Farewell & Departure', description: 'Final morning on the coast before transfer to Naples airport.', activities: ['Morning sea swim', 'Last espresso', 'Airport transfer'], accommodation: '', meals: { breakfast: true, lunch: false, dinner: false } },
    ],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');
    await Tour.deleteMany();
    console.log('Cleared existing tours');
    await Tour.insertMany(tours);
    console.log(`Seeded ${tours.length} tours with full itineraries`);
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seed();